name: "project_earthquakes"
version: "1.0.0"
config-version: 2

profile: "project_earthquakes"

model-paths: ["models"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  project_earthquakes:
    staging:
      +schema: project_earthquakes_gecko
      +materialized: view
    marts:
      +schema: project_earthquakes_gecko
      +materialized: table
